#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import json
import sys
# agent is a NethServer library which provides function to communicate with the agent
import agent
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)
data = json.load(sys.stdin)
# PAPERLESS_EMAIL_HOST=<str>
# Defaults to 'localhost'.
# PAPERLESS_EMAIL_PORT=<int>
# Defaults to port 25.
# PAPERLESS_EMAIL_HOST_USER=<str>
# Defaults to ''.
# PAPERLESS_EMAIL_FROM=<str>
# Defaults to PAPERLESS_EMAIL_HOST_USER if not set.
# PAPERLESS_EMAIL_HOST_PASSWORD=<str>
# Defaults to ''.
# PAPERLESS_EMAIL_USE_TLS=<bool>
# Defaults to false.
# PAPERLESS_EMAIL_USE_SSL=<bool>
# Setup default values
paperless_name = data.get("paperless_name","paperless-ngx")
PAPERLESS_ADMIN_USER = data.get("PAPERLESS_ADMIN_USER","paperlessadmin")
PAPERLESS_ADMIN_PASSWORD = data.get("PAPERLESS_ADMIN_PASSWORD","P@perle5$")
PAPERLESS_ADMIN_MAIL = data.get("PAPERLESS_ADMIN_MAIL","")
PAPERLESS_TIME_ZONE = data.get("PAPERLESS_TIME_ZONE","America/Los_Angeles")
PAPERLESS_OCR_LANGUAGE = data.get("PAPERLESS_OCR_LANGUAGE","eng")
PAPERLESS_COOKIE_PREFIX = data.get("PAPERLESS_COOKIE_PREFIX","paperlessngx")
PAPERLESS_FILENAME_FORMAT = data.get("PAPERLESS_FILENAME_FORMAT","{created_year}/{correspondent}/{doc_pk}-{title}")
# Email Settings
PAPERLESS_EMAIL_HOST = smtp_settings['host']
PAPERLESS_EMAIL_PORT = smtp_settings['port']
PAPERLESS_EMAIL_HOST_USER = smtp_settings['username']
PAPERLESS_EMAIL_FROM = smtp_settings['username']
PAPERLESS_EMAIL_HOST_PASSWORD = smtp_settings['password']
PAPERLESS_EMAIL_USE_TLS = 'true' if smtp_settings['tls_verify'] else 'false'
PAPERLESS_EMAIL_USE_SSL = 'false' if smtp_settings['tls_verify'] else 'true'
# PAperless CSRF settings
host = data.get("host", "")
PAPERLESS_URL = "https://"+host

paperless_config = {
    "PAPERLESS_NGX_NAME": paperless_name,
    "PAPERLESS_TIME_ZONE": PAPERLESS_TIME_ZONE,
    "PAPERLESS_OCR_LANGUAGE": PAPERLESS_OCR_LANGUAGE,
    "PAPERLESS_COOKIE_PREFIX": PAPERLESS_COOKIE_PREFIX,
    "PAPERLESS_ADMIN_USER": PAPERLESS_ADMIN_USER,
    "PAPERLESS_ADMIN_PASSWORD": PAPERLESS_ADMIN_PASSWORD,
    "PAPERLESS_ADMIN_MAIL": PAPERLESS_ADMIN_MAIL,
    "PAPERLESS_FILENAME_FORMAT": PAPERLESS_FILENAME_FORMAT,
    "PAPERLESS_URL": PAPERLESS_URL,
    "PAPERLESS_TIKA_ENABLED": "1",
    "PAPERLESS_TIKA_GOTENBERG_ENDPOINT": "http://127.0.0.1:3000",
    "PAPERLESS_TIKA_ENDPOINT": "http://127.0.0.1:9998",
    "PAPERLESS_EMAIL_HOST": PAPERLESS_EMAIL_HOST,
    "PAPERLESS_EMAIL_PORT": PAPERLESS_EMAIL_PORT,
    "PAPERLESS_EMAIL_HOST_USER": PAPERLESS_EMAIL_HOST_USER,
    "PAPERLESS_EMAIL_FROM": PAPERLESS_EMAIL_FROM,
    "PAPERLESS_EMAIL_HOST_PASSWORD": PAPERLESS_EMAIL_HOST_PASSWORD,
    "PAPERLESS_EMAIL_USE_TLS": PAPERLESS_EMAIL_USE_TLS,
    "PAPERLESS_EMAIL_USE_SSL": PAPERLESS_EMAIL_USE_SSL,

}

agent.write_envfile('paperless-ngx.env', paperless_config)


# Setup PHP with safe defaults
agent.set_env("PHP_ENABLE_OPCACHE", "1")
agent.set_env("PHP_MEMORY_LIMIT", "512M")


# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()
